# Generated by Django 3.2 on 2021-11-17 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=500)),
                ('icon', models.CharField(max_length=30)),
                ('texto', models.CharField(max_length=5000)),
                ('imagens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Precos_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('inicial', models.FloatField()),
                ('descricoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('mensagemFlayer1', models.CharField(max_length=250)),
                ('mensagemFlayer2', models.CharField(max_length=250)),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Carrocel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.imagem')),
            ],
        ),
    ]
