# Generated by Django 3.2 on 2021-11-21 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Opcoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Precos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('valorMensal', models.FloatField()),
                ('valorAnual', models.FloatField()),
                ('extra', models.CharField(max_length=100)),
                ('opcoes', models.ManyToManyField(blank=True, null=True, to='landing.Opcoes')),
            ],
        ),
        migrations.AddField(
            model_name='precos_services',
            name='preco',
            field=models.ManyToManyField(blank=True, null=True, to='landing.Precos'),
        ),
        migrations.AddField(
            model_name='servicos',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.card'),
        ),
        migrations.AddField(
            model_name='servicos',
            name='precos_servico',
            field=models.ManyToManyField(blank=True, null=True, to='landing.Precos'),
        ),
        migrations.AddField(
            model_name='servicos',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.tag'),
        ),
    ]
