# Generated by Django 3.2 on 2021-11-28 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20211125_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='carrocel',
            name='imagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='landing.imagem'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='imagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='landing.imagem'),
        ),
        migrations.AlterField(
            model_name='precos_services',
            name='descricoes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='landing.descricao'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='imagens',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='landing.imagem'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='landing.tag'),
        ),
    ]
