# Generated by Django 3.2 on 2021-11-28 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_visitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='imagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='landing.upload'),
        ),
    ]
