# Generated by Django 3.2 on 2021-11-28 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_alter_landing_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='imagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.upload'),
        ),
        migrations.AlterField(
            model_name='carrocel',
            name='imagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='landing.upload'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='imagens',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='landing.upload'),
        ),
    ]
