# Generated by Django 3.2 on 2021-11-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_auto_20211128_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='imagem',
            field=models.CharField(max_length=250),
        ),
    ]
