# Generated by Django 3.2 on 2021-11-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_alter_landing_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='imagem',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='carrocel',
            name='imagem',
            field=models.CharField(max_length=250),
        ),
    ]
