# Generated by Django 3.2 on 2021-11-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_auto_20211128_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicos',
            name='imagens',
        ),
        migrations.AddField(
            model_name='servicos',
            name='imagem',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
