# Generated by Django 3.2 on 2021-12-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_auto_20211129_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('hash', models.CharField(max_length=500)),
                ('dir', models.CharField(max_length=500)),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
    ]
