# Generated by Django 3.2 on 2021-12-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_testenvio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('hash', models.CharField(max_length=500)),
                ('dir', models.CharField(max_length=500)),
                ('imagem', models.CharField(max_length=100000)),
            ],
        ),
        migrations.DeleteModel(
            name='TestEnvio',
        ),
    ]
