# Generated by Django 3.2 on 2021-12-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_auto_20211217_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='imagem',
            field=models.BinaryField(),
        ),
    ]
