# Generated by Django 3.2 on 2022-01-26 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0020_enviorelatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EnvioImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('hash', models.CharField(max_length=500)),
                ('dir', models.CharField(max_length=500)),
                ('pagina', models.IntegerField()),
                ('imagem', models.TextField()),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.caixa')),
            ],
        ),
        migrations.DeleteModel(
            name='Envio',
        ),
    ]
