# Generated by Django 3.2 on 2022-01-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0021_auto_20220126_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envioimagem',
            name='caixa',
            field=models.IntegerField(),
        ),
    ]
