# Generated by Django 3.2 on 2022-01-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0022_alter_envioimagem_caixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envioimagem',
            name='imagem',
            field=models.CharField(max_length=50000),
        ),
    ]
