# Generated by Django 3.2 on 2022-01-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0023_alter_envioimagem_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envioimagem',
            name='caixa',
            field=models.CharField(max_length=500),
        ),
    ]
