# Generated by Django 3.2 on 2022-01-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0024_alter_envioimagem_caixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envioimagem',
            name='caixa',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='envioimagem',
            name='dir',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='envioimagem',
            name='hash',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='envioimagem',
            name='imagem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='envioimagem',
            name='nome',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='envioimagem',
            name='pagina',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
