# Generated by Django 3.2 on 2022-01-31 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0025_auto_20220126_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('datatime', models.DateTimeField()),
                ('output', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
