# Generated by Django 3.2 on 2022-01-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0027_alter_logs_datatime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='output',
            field=models.CharField(max_length=5000),
        ),
    ]
