# Generated by Django 3.2 on 2022-01-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0029_rename_logs_logssenders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logssenders',
            name='datatime',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='logssenders',
            name='output',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='logssenders',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
