# Generated by Django 3.2 on 2022-01-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0030_auto_20220131_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='LogsSenders',
        ),
    ]
