# Generated by Django 3.2 on 2022-02-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0031_auto_20220131_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caixa',
        ),
    ]
