# Generated by Django 3.2 on 2022-02-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0032_delete_caixa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(blank=True, max_length=500, null=True)),
                ('Tag', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
