# Generated by Django 3.2 on 2022-02-15 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0033_caixa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caixa',
        ),
    ]
